server {
        server_name blog.s1th.in s1th.in;
        location /blog {
                proxy_pass http://spring-boot-app/blogs;
        }
        location / {
                proxy_pass http://spring-boot-app/blogs;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/blog.s1th.in/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/blog.s1th.in/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = blog.s1th.in) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = s1th.in) {
        return 301 https://$host$request_uri;
    }


        listen 80;
        server_name blog.s1th.in;
    return 404; # managed by Certbot
}
