spring.application.name=simple-rest-api

logging.file.name=logs/app.log
management.endpoints.web.exposure.include=health,info,logfile,metrics

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hikari Connection Pool
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ===============================
# JPA / Hibernate
# ===============================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=31
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.stat=DEBUG
logging.level.org.hibernate.stat.internal=DEBUG