CREATE TABLE customers (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    first_name varchar(255) NULL,
    last_name varchar(255) NULL,
    company varchar(255) NULL,
    city varchar(255) NULL,
    country varchar(255) NULL,
    phone_1 varchar(255) NULL,
    phone_2 varchar(255) NULL,
    email varchar(255) NULL,
    subscription_date varchar(255) NULL,
    website_url varchar(255) NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE orders (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    customer_id int8 NOT NULL,
    order_date date NOT NULL,
    status varchar(30) NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    shipping_amount numeric(10, 2) NOT NULL,
    payment_method varchar(30) NOT NULL,
    shipping_city varchar(100) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
    user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    first_name varchar(255) NULL,
    last_name varchar(255) NULL,
    user_email varchar(255) NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    updated_by varchar(255) NULL,
    is_deleted bool DEFAULT false NULL,
    deleted_at timestamp NULL,
    deleted_by varchar(255) NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE habits (
    habit_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    habit_name varchar(255) NULL,
    habit_description varchar(1000) NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    created_by varchar(255) NULL,
    updated_by varchar(255) NULL,
    is_deleted bool DEFAULT false NOT NULL,
    deleted_at timestamp NULL,
    deleted_by varchar(255) NULL,
    CONSTRAINT pk_habits PRIMARY KEY (habit_id)
);

CREATE TABLE habit_tracker (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    is_habit_completed bool DEFAULT false NOT NULL,
    user_id int8 NULL,
    habit_id int8 NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    created_by varchar(255) NULL,
    updated_by varchar(255) NULL,
    habit_date varchar(255) NULL,
    CONSTRAINT pk_habit_tracker PRIMARY KEY (id),
    CONSTRAINT fk_habit_tracker_habit FOREIGN KEY (habit_id) REFERENCES public.habits(habit_id),
    CONSTRAINT fk_habit_tracker_user FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);